trigger:
  branches:
    include:
      - main

pool:
  name: Default
  demands:
    - agent.name -equals DESKTOP-EC8HHP6

stages:
  - stage: Build_Backend
    displayName: "Build Spring Boot Backend"
    jobs:
      - job: BackendJob
        displayName: "Backend - Build & Test"
        steps:
          - script: |
              echo === Utilisation de Java installé localement ===
              java -version
              cd ExamPortal-master
              mvnw.cmd clean verify
            displayName: 'Build Backend'

          - script: |
              cd ExamPortal-master
              mvnw.cmd test
            displayName: 'Test Backend'

  - stage: Build_Frontend
    displayName: "Build Angular Frontend"
    dependsOn: Build_Backend
    jobs:
      - job: FrontendJob
        displayName: "Frontend - Build & Test"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js 18'

          - script: |
              cd ExamPortalAngularGUI-main
              npm install
              npm run build
            displayName: 'Build Angular App'

          - script: |
              cd ExamPortalAngularGUI-main
              npm test -- --watch=false --browsers=ChromeHeadless
            displayName: 'Run Frontend Tests'
