trigger:
- main

# Utilisation de ton agent local
pool:
  name: Default   # nom du pool (vérifie s’il est différent dans Azure DevOps)
  demands:
    - agent.name -equals DESKTOP-EC8HHP6  # nom exact de l’agent installé sur ta machine

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
